project:
  type: website
  resources:
    - cv.pdf
    - CNAME

website:
  title: "Ceren F. Eser"
  search: false
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.pdf

format:
  html:
    theme: [litera, styles.scss]
    embed-resources: true
    toc: false
    fontsize: 1.05em
