project:
  type: website

website:
  title: "Ceren F. Eser"
  search: false
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd

format:
  html:
    theme: [litera, styles.scss]
    toc: false
    fontsize: 1.05em
